services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017" # Map the container's 27017 to 27018 on the localhost, as it's overlapping with local mongodb
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=0
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app/app
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
