version: '3'

services:

  app:
    build: .
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=0
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app/app
    networks:
      - app-network

networks:
  app-network:

