apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test
  namespace: kubernetes-test
  labels:
    app: kubernetes-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-test
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
      - name: kubernetes-test
        image: 034362071134.dkr.ecr.eu-west-2.amazonaws.com/playground-2:latest
        ports:
        - containerPort: 5000 
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: kubernetes-test-app-secret
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubernetes-test-app-secret
                key: MONGO_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: kubernetes-test-app-secret
                key: SECRET_KEY
          - name: MONGODB_URI
            value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@10.0.13.144:27017/security_hub?authSource=admin"
