apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-cslh
  namespace: prod-cslh-namespace
  labels:
    app: prod-cslh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-cslh
  template:
    metadata:
      labels:
        app: prod-cslh
    spec:
      serviceAccountName: prod-cslh-admin  # 🚨 This gives the pod cluster-admin access
      containers:
      - name: prod-cslh
        image: 050451363468.dkr.ecr.us-east-2.amazonaws.com/prod-cslh:latest  # This will be dynamically replaced by GitHub Actions
        ports:
        - containerPort: 5000 
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: prod-cslh-app-secret
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-cslh-app-secret
                key: MONGO_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: prod-cslh-app-secret
                key: SECRET_KEY
          - name: MONGODB_URI
            value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@10.0.1.174:27017/security_hub?authSource=admin"
      imagePullSecrets:
      - name: regcred  # Optional: If you need private registry credentials