apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-service
  namespace: kubernetes-test
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000