apiVersion: v1
kind: Service
metadata:
  name: prod-cslh-lb-service
  namespace: prod-cslh-namespace
spec:
  type: LoadBalancer
  selector:
    app: prod-cslh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000