apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-cslh-admin
  namespace: prod-cslh-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prod-cslh-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prod-cslh-admin
  namespace: prod-cslh-namespace